[package]
authors = ["Microsoft"]
description = "Code gen support for the windows crate"
documentation = "https://microsoft.github.io/windows-docs-rs/"
edition = "2018"
license = "MIT OR Apache-2.0"
name = "windows-targets"
repository = "https://github.com/microsoft/windows-rs"
version = "0.42.1"
[target.aarch64-pc-windows-gnullvm.dependencies.windows_aarch64_gnullvm]
version = "0.42.1"
[target.aarch64-pc-windows-msvc.dependencies.windows_aarch64_msvc]
version = "0.42.1"
[target.aarch64-uwp-windows-msvc.dependencies.windows_aarch64_msvc]
version = "0.42.1"
[target.i686-pc-windows-gnu.dependencies.windows_i686_gnu]
version = "0.42.1"
[target.i686-pc-windows-msvc.dependencies.windows_i686_msvc]
version = "0.42.1"
[target.i686-uwp-windows-gnu.dependencies.windows_i686_gnu]
version = "0.42.1"
[target.i686-uwp-windows-msvc.dependencies.windows_i686_msvc]
version = "0.42.1"
[target.x86_64-pc-windows-gnu.dependencies.windows_x86_64_gnu]
version = "0.42.1"
[target.x86_64-pc-windows-gnullvm.dependencies.windows_x86_64_gnullvm]
version = "0.42.1"
[target.x86_64-pc-windows-msvc.dependencies.windows_x86_64_msvc]
version = "0.42.1"
[target.x86_64-uwp-windows-gnu.dependencies.windows_x86_64_gnu]
version = "0.42.1"
[target.x86_64-uwp-windows-msvc.dependencies.windows_x86_64_msvc]
version = "0.42.1"
